class Team < ActiveRecord::Base

end

# t.string   "highlight_tags"
# t.text     "branding"
# t.text     "headline"
# t.text     "big_quote"
# t.string   "big_image"
# t.string   "featured_banner_image"
# t.text     "benefit_name_1"
# t.text     "benefit_description_1"
# t.text     "benefit_name_2"
# t.text     "benefit_description_2"
# t.text     "benefit_name_3"
# t.text     "benefit_description_3"
# t.text     "reason_name_1"
# t.text     "reason_description_1"
# t.text     "reason_name_2"
# t.text     "reason_description_2"
# t.text     "reason_name_3"
# t.text     "reason_description_3"
# t.text     "why_work_image"
# t.text     "organization_way"
# t.text     "organization_way_name"
# t.text     "organization_way_photo"
# t.text     "blog_feed"
# t.text     "our_challenge"
# t.text     "your_impact"
# t.text     "hiring_tagline"
# t.text     "link_to_careers_page"
# t.text     "stack_list",                                               :default => t.string   "office_photos",                                            :default => t.text     "interview_steps",                                          :default =>
